if (!document.querySelector('#authModal')) document.body.insertAdjacentHTML('beforeend', `<div class="modal auth-modal" id="authModal" aria-hidden="true"><div class="modal-card auth-card"><button class="close-auth" aria-label="Close account">×</button><div class="auth-mark">☾</div><div id="authGuest"><p class="eyebrow dark">Your account</p><h2>Welcome to the circle</h2><p class="auth-intro">Create an account or sign in to keep your orders connected to you.</p><div class="auth-tabs"><button class="active" type="button" data-auth-mode="signin">Sign in</button><button type="button" data-auth-mode="signup">Sign up</button></div><form id="authForm"><label class="signup-only" hidden>Full name<input id="signupName" autocomplete="name" placeholder="Your name"></label><label class="signup-only" hidden>Mobile number<input id="signupMobile" type="tel" autocomplete="tel" placeholder="+91 98765 43210"></label><label>Email address<input id="authEmail" type="email" required autocomplete="email" placeholder="you@example.com"></label><label>Password<input id="authPassword" type="password" required minlength="8" autocomplete="current-password" placeholder="Minimum 8 characters"></label><button class="button primary" type="submit" id="authSubmit">Sign in</button></form><form id="signupOtpForm" hidden><p>We sent a verification code to <strong id="signupOtpEmail"></strong>.</p><label>Email OTP<input id="signupOtp" inputmode="numeric" autocomplete="one-time-code" minlength="6" maxlength="8" pattern="[0-9]{6,8}" required placeholder="Enter email code"></label><button class="button primary" type="submit">Verify account</button><button class="auth-link" id="backToSignup" type="button">Back to sign up</button></form><small class="auth-status" id="authStatus"></small></div><div id="authUser" hidden><p class="eyebrow dark">Signed in</p><h2>Your account</h2><div class="user-avatar">✦</div><strong id="userName"></strong><span id="userEmail"></span><span id="userMobile"></span><p>Your saved details will be used to make checkout faster.</p><button class="button primary" id="logoutUser" type="button">Sign out</button></div></div></div>`);
if (!document.querySelector('link[href="auth-extra.css"]')) document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="auth-extra.css">');
document.querySelector('#signupOtp').maxLength = 6; document.querySelector('#signupOtp').minLength = 6; document.querySelector('#signupOtp').pattern = '[0-9]{6}';
document.querySelector('#backToSignup').insertAdjacentHTML('beforebegin', '<button class="auth-link" id="resendSignupOtp" type="button">Resend OTP</button>');
let authMode = 'signin', supabaseClient = null, pendingSignupEmail = '';
const authModal = document.querySelector('#authModal'), authStatus = document.querySelector('#authStatus');
const authConfigured = () => window.SUPABASE_CONFIG?.url && window.SUPABASE_CONFIG?.anonKey && window.supabase;
function openAuth() { authModal.classList.add('open'); authModal.setAttribute('aria-hidden', 'false') }
function closeAuth() { authModal.classList.remove('open'); authModal.setAttribute('aria-hidden', 'true'); authStatus.textContent = '' }
function publishUser(user) { window.currentInfinityUser = user || null; window.dispatchEvent(new CustomEvent('infinity-auth-user', { detail: user || null })) }
function showSignedOut() { document.querySelector('#authGuest').hidden = false; document.querySelector('#authUser').hidden = true; document.querySelector('#accountButton').textContent = 'Sign in'; publishUser(null) }
function showSignedIn(user) { const meta = user.user_metadata || {}; document.querySelector('#authGuest').hidden = true; document.querySelector('#authUser').hidden = false; document.querySelector('#userName').textContent = meta.full_name || 'Infinity Divine member'; document.querySelector('#userEmail').textContent = user.email || ''; document.querySelector('#userMobile').textContent = meta.mobile || ''; document.querySelector('#accountButton').textContent = meta.full_name || user.email; publishUser(user) }
function setupMessage() { authStatus.textContent = 'Account login is awaiting Supabase setup. Add the project URL and public key first.' }
function setMode(mode) { authMode = mode; document.querySelectorAll('[data-auth-mode]').forEach(b => b.classList.toggle('active', b.dataset.authMode === mode)); document.querySelectorAll('.signup-only').forEach(el => { el.hidden = mode !== 'signup'; el.querySelector('input').required = mode === 'signup' }); document.querySelector('#authPassword').autocomplete = mode === 'signup' ? 'new-password' : 'current-password'; document.querySelector('#authSubmit').textContent = mode === 'signup' ? 'Create account' : 'Sign in'; document.querySelector('#authForm').hidden = false; document.querySelector('#signupOtpForm').hidden = true; authStatus.textContent = '' }
document.querySelector('#accountButton').addEventListener('click', openAuth); document.querySelector('.close-auth').addEventListener('click', closeAuth); authModal.addEventListener('click', e => { if (e.target === authModal) closeAuth() }); document.querySelectorAll('[data-auth-mode]').forEach(button => button.addEventListener('click', () => setMode(button.dataset.authMode))); document.querySelector('#backToSignup').addEventListener('click', () => setMode('signup')); document.querySelector('#resendSignupOtp').addEventListener('click', async e => { if (!pendingSignupEmail) return; const button = e.currentTarget; button.disabled = true; authStatus.textContent = 'Sending a new OTP…'; const { error } = await supabaseClient.auth.resend({ type: 'signup', email: pendingSignupEmail }); button.disabled = false; authStatus.textContent = error ? error.message : 'A new OTP was sent. Check Inbox and Spam.' });
document.querySelector('#authForm').addEventListener('submit', async e => { e.preventDefault(); if (!authConfigured()) { setupMessage(); return } const email = document.querySelector('#authEmail').value.trim().toLowerCase(), password = document.querySelector('#authPassword').value, button = document.querySelector('#authSubmit'); button.disabled = true; button.textContent = authMode === 'signup' ? 'Creating account…' : 'Signing in…'; authStatus.textContent = ''; if (authMode === 'signin') { const { data, error } = await supabaseClient.auth.signInWithPassword({ email, password }); button.disabled = false; button.textContent = 'Sign in'; if (error) { authStatus.textContent = error.message; return } showSignedIn(data.user); e.target.reset(); setTimeout(closeAuth, 700); return } const fullName = document.querySelector('#signupName').value.trim(), mobile = document.querySelector('#signupMobile').value.trim(); const { data, error } = await supabaseClient.auth.signUp({ email, password, options: { data: { full_name: fullName, mobile } } }); button.disabled = false; button.textContent = 'Create account'; if (error) { authStatus.textContent = error.message; return } if (data.session) { showSignedIn(data.user); e.target.reset(); setTimeout(closeAuth, 700); return } pendingSignupEmail = email; document.querySelector('#signupOtpEmail').textContent = email; document.querySelector('#authForm').hidden = true; document.querySelector('#signupOtpForm').hidden = false; authStatus.textContent = 'Enter the OTP from your email to activate your account.'; document.querySelector('#signupOtp').focus() });
document.querySelector('#signupOtpForm').addEventListener('submit', async e => { e.preventDefault(); authStatus.textContent = 'Verifying account…'; const { data, error } = await supabaseClient.auth.verifyOtp({ email: pendingSignupEmail, token: document.querySelector('#signupOtp').value, type: 'signup' }); if (error) { authStatus.textContent = error.message; return } showSignedIn(data.user); e.target.reset(); document.querySelector('#authForm').reset(); authStatus.textContent = 'Account verified successfully.'; setTimeout(closeAuth, 900) });
document.querySelector('#logoutUser').addEventListener('click', async () => { if (supabaseClient) await supabaseClient.auth.signOut(); showSignedOut(); closeAuth() });
if (authConfigured()) { supabaseClient = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.anonKey); supabaseClient.auth.getUser().then(({ data }) => data.user ? showSignedIn(data.user) : showSignedOut()); supabaseClient.auth.onAuthStateChange((_event, session) => session?.user ? showSignedIn(session.user) : showSignedOut()) } else showSignedOut();
