if(!document.querySelector('link[href="shop-page.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="shop-page.css">');
let shopProducts=window.getProducts(),shopCart=window.getCart();const grid=document.querySelector('#productGrid');
const esc=value=>{const d=document.createElement('div');d.textContent=value||'';return d.innerHTML};
function renderProducts(filter='All'){const shown=filter==='All'?shopProducts:shopProducts.filter(p=>p.category===filter);grid.innerHTML=shown.map(p=>`<article class="product-card" data-product-id="${p.id}" tabindex="0" role="link" aria-label="View ${esc(p.name)} details">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}<div class="product-art" style="background:linear-gradient(145deg,${p.color}33,#eee7dd)">${p.image?`<img class="product-image" src="${p.image}" alt="${esc(p.name)}">`:`<div class="${p.type}" style="--stone:${p.color}"></div>`}</div><div class="product-info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="product-bottom"><strong>${window.formatMoney(p.price)}</strong><button class="add-cart" data-add="${p.id}">Add to bag +</button></div></div></article>`).join('')}
function updateBag(){shopCart=shopCart.filter(id=>shopProducts.some(p=>p.id===id));window.saveCart(shopCart);document.querySelector('#cartCount').textContent=shopCart.length;const items=document.querySelector('#cartItems');items.innerHTML=shopCart.length?shopCart.map((id,i)=>{const p=shopProducts.find(x=>x.id===id);return `<div class="cart-item"><div class="cart-thumb" style="background:${p.color}22">${p.image?`<img src="${p.image}" alt="">`:(p.type==='crystal'?'♦':'◌')}</div><div><h4>${esc(p.name)}</h4><small>${window.formatMoney(p.price)}</small></div><button data-remove="${i}">×</button></div>`}).join(''):'<div class="empty-cart">Your bag is waiting for a little magic. ✦</div>';document.querySelector('#cartTotal').textContent=window.formatMoney(shopCart.reduce((sum,id)=>sum+shopProducts.find(p=>p.id===id).price,0))}
function openBag(){document.body.classList.add('cart-open')}function closeBag(){document.body.classList.remove('cart-open')}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){shopCart.push(Number(add.dataset.add));updateBag();toast('Added to your bag ✦')}const remove=e.target.closest('[data-remove]');if(remove){shopCart.splice(Number(remove.dataset.remove),1);updateBag()}const filter=e.target.closest('[data-filter]');if(filter){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));renderProducts(filter.dataset.filter)}if(e.target.closest('#openBag'))openBag();if(e.target.closest('.close-cart')||e.target.classList.contains('drawer-backdrop'))closeBag();if(e.target.closest('.menu-toggle'))document.querySelector('.main-nav').classList.toggle('open')});
const initial=new URLSearchParams(location.search).get('filter')||'All';const initialButton=document.querySelector(`[data-filter="${initial}"]`);if(initialButton){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===initialButton))}renderProducts(initial);updateBag();if(location.hash==='#bag')openBag();
document.addEventListener('click',e=>{const card=e.target.closest('[data-product-id]');if(card&&!e.target.closest('[data-add]'))location.href=`product.html?id=${card.dataset.productId}`});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-product-id]'))location.href=`product.html?id=${e.target.dataset.productId}`});
